services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    user: root
    ports:
      - "6001:6001" # Changed both external and internal port to 6001
    command: ["start", "--bind", "0.0.0.0:6001", "file://data/srdb.db"]
    volumes:
      - surrealdb_data:/data

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "6002:6002" # Changed both external and internal port to 6002
    command: ["--port=6002"]
    volumes:
      - dragonfly_data:/data

  centrifugal:
    image: centrifugo/centrifugo
    command: centrifugo -c config.json --engine=redis --redis_address=redis://dragonfly:6002 --port=6003
    depends_on:
      - dragonfly
    ports:
      - "6003:6003" # Changed both external and internal port to 6003
    volumes:
      - "./config:/centrifugo"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

  web:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Kept port as 3000

volumes:
  surrealdb_data:
  dragonfly_data:
